/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
  Drupal.AjaxCommands.prototype.showPopup = function (ajax, response) {
    var popup = Popup.register(response.data, response.id).open();

    popup.element.querySelectorAll = document.querySelectorAll.bind(document);
    Drupal.attachBehaviors(popup.element, drupalSettings);
  };

  Drupal.AjaxCommands.prototype.closePopup = function (ajax, response) {
    Popup.close(response.id);
  };
})(jQuery, Drupal, drupalSettings);